import L from 'leaflet';

export const icons = {
      kozbiztonsag: L.icon({
    iconUrl: '/icons/alap-kozbiztonsag.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
      muhold: L.icon({
    iconUrl: '/icons/alap-muhold.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
      kozlek: L.icon({
    iconUrl: '/icons/alap-kozlek.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
      bank: L.icon({
    iconUrl: '/icons/alap-bank.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
      sport: L.icon({
    iconUrl: '/icons/alap-sport.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
      oktatas: L.icon({
    iconUrl: '/icons/alap-oktatas.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
    szabad: L.icon({
    iconUrl: '/icons/alap-szabad.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
    vallas: L.icon({
    iconUrl: '/icons/alap-vallas.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
    egeszsegugy: L.icon({
    iconUrl: '/icons/alap-eu.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
    bolt: L.icon({
    iconUrl: '/icons/alap-bolt.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  christian: L.icon({
    iconUrl: '/icons/christianity.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  muslim: L.icon({
    iconUrl: '/icons/islam.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  jewish: L.icon({
    iconUrl: '/icons/jewish.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  hospital: L.icon({
    iconUrl: '/icons/hospital.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  pharmacy: L.icon({
    iconUrl: '/icons/pharmacy.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  dentist: L.icon({
    iconUrl: '/icons/dentist.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  veterinarian: L.icon({
    iconUrl: '/icons/veterinary.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  doctor: L.icon({
    iconUrl: '/icons/stethoscope.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  kindergarten: L.icon({
    iconUrl: '/icons/kindergarten.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  school: L.icon({
    iconUrl: '/icons/school.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  secondaryschool: L.icon({
    iconUrl: '/icons/secondaryschool.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  university: L.icon({
    iconUrl: '/icons/university.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  shop: L.icon({
    iconUrl: '/icons/shop.png',
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  // Új ikonok a szabadtér réteghez
  playground: L.icon({
    iconUrl: '/icons/playground.png', // Játszótér ikon (pl. hinta vagy csúszda)
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  dogPark: L.icon({
    iconUrl: '/icons/dog_park.png', // Kutyafuttató ikon (pl. kutya sziluett)
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  nature: L.icon({
    iconUrl: '/icons/nature.png', // Természet/erdő ikon (pl. fa vagy hegy)
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
  park: L.icon({
    iconUrl: '/icons/park.png', // Park/kert ikon (pl. zöld fa vagy pad)
    iconSize: [25, 25],
    iconAnchor: [12, 12],
    shadowUrl: '/icons/shadow.png',
    shadowSize: [25, 25],
    shadowAnchor: [12, 12],
    className: 'layer-marker-icon',
  }),
// Új sport réteg ikonok
gym: L.icon({
  iconUrl: '/icons/gym.png', // Konditerem ikon (pl. súlyzó)
  iconSize: [25, 25],
  iconAnchor: [12, 12],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [25, 25],
  shadowAnchor: [12, 12],
  className: 'layer-marker-icon',
}),
streetWorkout: L.icon({
  iconUrl: '/icons/street_workout.png', // Street workout ikon (pl. húzódzkodó)
  iconSize: [25, 25],
  iconAnchor: [12, 12],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [25, 25],
  shadowAnchor: [12, 12],
  className: 'layer-marker-icon',
}),
pitch: L.icon({
  iconUrl: '/icons/pitch.png', // Foci/kosárpálya ikon (pl. labda)
  iconSize: [25, 25],
  iconAnchor: [12, 12],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [25, 25],
  shadowAnchor: [12, 12],
  className: 'layer-marker-icon',
}),
waterSports: L.icon({
  iconUrl: '/icons/water_sports.png', // Vízisport ikon (pl. evező vagy hullám)
  iconSize: [25, 25],
  iconAnchor: [12, 12],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [25, 25],
  shadowAnchor: [12, 12],
  className: 'layer-marker-icon',
}),

bank: L.icon({
  iconUrl: '/icons/bank.png', // Bankfiók ikon (pl. banképület vagy pénzérme)
  iconSize: [25, 25],
  iconAnchor: [12, 12],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [25, 25],
  shadowAnchor: [12, 12],
  className: 'layer-marker-icon',
}),
atm: L.icon({
  iconUrl: '/icons/atm.png', // ATM ikon (pl. kártya vagy kis automata)
  iconSize: [20, 20], // Kicsit kisebb, hogy megkülönböztethető legyen
  iconAnchor: [10, 10],
  shadowUrl: '/icons/shadow.png',
  shadowSize: [20, 20],
  shadowAnchor: [10, 10],
  className: 'layer-marker-icon',
}),
};